version: "3.9"  # optional since v1.27.0
services:
    mongodb: 
        image: mongo:4-bionic
        volumes: 
            - ./auth/data:/data/db
        ports: 
            - 5000: 80
    auth: 
        build: ./auth
        depends_on: 
            - mongodb
        volumes: 
            - ./auth:/usr/src/app
        environment:
            JWT_SECRET: ${JWT_SECRET}
            MONGODB_URL: ${MONGODB_URL}
        ports: 
            - 5001: 80
    app: 
        build: ./app
        volumes: 
            - ./app:/usr/src/app
        ports: 
            - 5002: 80
    ghi:
        build: ./ghi
        volumes: 
            - ./ghi:/todos.conf
        ports: 
            - 5003: 80